spring.application.name=pay
#logging.level.org.hibernate.SQL=DEBUG
# Enable the H2 console for viewing the DB content (optional, useful for development)
# spring.h2.console.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Enable virtual threads
spring.threads.virtual.enabled=true
# Essential PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=genpay
spring.datasource.driver-class-name=org.postgresql.Driver
#Optional: Hibernate 6+ automatically resolves the dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# Increase pool size if your Postgres server can handle it (default is 10)
spring.datasource.hikari.maximum-pool-size=20
# Ensure connections aren't held too long
spring.datasource.hikari.idle-timeout=30000
# Disable the tracing
management.tracing.enabled=false
management.otlp.metrics.export.enabled=false
